// react-webpack/src/containers/Home/index.jsx
import React, {Component} from 'react';
import {connect} from 'react-redux';
import {Button} from 'antd-mobile';
import axios from 'axios'

import {homeAction} from 'reduxs/action';

@connect(
  state => state.home,
  {homeAction}
)
class Home extends Component {
  constructor(props){
    super(props);
    this.onChange = this.onChange.bind(this);
  }

  componentWillMount() {
    axios.get('/api/current')
      .then(res => {
        console.log(res);
      }).catch(err => console.log(err))

  }

  onChange(){
    this.props.homeAction({react:"webpack3"});
  }

  render() {
    return (
      <section>
        {this.props.react}
        <Button onClick={this.onChange}>click</Button>
        </section>
    );
  }
}

export default Home;

// vue-webpack/src/containers/home/index.vue
<template>
  <div>
    home
    <p>取vuex值{{this.home.webpack}}</p>
    <mt-button type="primary" @click="submitHomeAction">提交Actions</mt-button>
  </div>
</template>

<script type="text/ecmascript-6">
  import axios from 'axios'
  import {mapGetters, mapMutations, mapActions} from 'vuex'

  export default {
    data() {
      return {
        result: {},
      }
    },
    computed: {
      ...mapGetters([
        'home'
      ])
    },
    created() {
      axios.get('/api/current')
        .then(res => {
          console.log(res);
        }).catch(err => {
        console.log(err)
      })
    },
    methods: {
      ...mapMutations({
        homeMutation: 'SET_HOME'
      }),
      ...mapActions([
        'homeAction',
      ]),
      submitHomeAction(){
        this.homeAction({webpack:'vue2'});
        setTimeout(()=>{
          this.homeMutation({webpack:'vue'});
        },2000)
      }
    }
  }
</script>

<style lang="scss">

</style>
